### ISSUE TITLE
v0.2.0 tracker - Don't use

### ISSUE THREAD

**Issue by alexwkleung** [alexwkleung/Iris#2]
# Tracker for v0.2.0

This will be updated periodically.

## To-do
- [ ] Major source code clean up and refactor
- [ ] Custom WYSIWYG editor
- [ ] UI clean up
- [ ] Add delete folder
- [ ] Add rename folder
- [ ] Add move file
- [ ] Add context menu 
- [ ] Add user custom themes
- [ ] Automatically sort folders and notes (alphabetically)
- [ ] Handle duplicate folder and file names (only allow unique names)
- [ ] App icon
- [ ] Preserve file state on app quit and restore it on startup
- [ ] Code sign builds
- [ ] Supply both x64 and arm64 macOS builds in new releases
- [ ] Cross-platform desktop support

## Finished (after core cleanup)

TBA  

## Finished (before core cleanup)

- [x] Create a basic directory tree (initial progress in [tauri-dir-tree-struct](https://github.com/alexwkleung/tauri-dir-tree-struct) repo)
- [x] Switch to napi-rs + electron-vite (eaa485b)
- [x] Opened file indicator in directory tree (a18e53f)
- [x] Add auto save (f119953)
- [x] Long file and folder names should be handled properly for better UX (902e128, 1974dce)
- [x] Frameless window (56bea4c)
- [x] UI elements should retain its layout (no deformation of elements) when resizing or fullscreen-ing the window (5ea1f6e - current UI)
- [x] Replace Milkdown with a vanilla ProseMirror WYSIWYG Markdown editor implementation (2b26457 - initial)
- [x] Allow external image URL's to be pasted in editor (3c110c6, 26f77d9)
- [x] Add directory information top bar  (a970592)
- [x] Add ProseMirror menu bar (3a14aa5)
- [x] Word count (56d1992)
- [x] Allow copying WYSIWYG editor content as Markdown (d6aed4f)
- [x] Add create file (dd50215)
- [x] Add insert tab (529ba1e)
- [x] Add create folder (b429c75)
- [x] File count beside folder name (e8be9bd)
- [x] Automatically create app directory on startup if it doesn't exist (0471b87)
- [x] Automatically open newly created file in editor (4b37729)
- [x] Add delete file (8ede19f)
- [x] Dark/light theme + toggle
- [x] Reduce app size (7404267 - for now) 
- [x] New UI 
- [x] App settings using JSON as data persistence (71ce585 - themes)
- [x] Add rename file (dbea0ac)
- [x] Cursor options for advanced editor (2706335)
- [x] Editor switching between basic and advanced
- [x] Reading mode (7ea95aa)
- [x] Code syntax highlighting in reading mode (f306a39)
- [x] Math and diagram support in reading mode (51a6434)
- [x] Product website (https://irisnotes.vercel.app/)
